// flow-typed signature: 83c79fe51c1cb72b98b6444e88fe6e51
// flow-typed version: <<STUB>>/@types/agenda_v^0.8.33/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/agenda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/agenda' {
  declare module.exports: any;
}
