// flow-typed signature: b35b110bf57f8f73f4fbcb3ff038b682
// flow-typed version: <<STUB>>/@types/body-parser_v^0.0.33/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/body-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/body-parser' {
  declare module.exports: any;
}
