// flow-typed signature: 3c625d5728ce57b5768ff46c30fba8c9
// flow-typed version: <<STUB>>/@types/body-parser_v^0.0.33/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/body-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/body-parser' {
  declare module.exports: any;
}
