// flow-typed signature: 5f7a0d67dc7193112d3bc395b8c8b552
// flow-typed version: <<STUB>>/@types/bytes_v^2.4.33/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/bytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/bytes' {
  declare module.exports: any;
}
