// flow-typed signature: 486b02be1c1e38888d4db41f7d84327a
// flow-typed version: <<STUB>>/@types/cors_v^0.0.33/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/cors' {
  declare module.exports: any;
}
