// flow-typed signature: f845fdb3924982b59eb59c9f7c3c7665
// flow-typed version: <<STUB>>/@types/cors_v^2.8.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/cors' {
  declare module.exports: any;
}
