// flow-typed signature: 4ee9ca964e78e9d770b3a2203b86b170
// flow-typed version: <<STUB>>/@types/date-fns_v^2.6.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/date-fns' {
  declare module.exports: any;
}
