// flow-typed signature: cbe624d8d0f9accb02c886efcbeb72f7
// flow-typed version: <<STUB>>/@types/express_v^4.0.34/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
