// flow-typed signature: 611f0fd5674efdfa05a778f1155ed956
// flow-typed version: <<STUB>>/@types/graphql_v^0.8.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/graphql' {
  declare module.exports: any;
}
