// flow-typed signature: 8cc56d1474e3c7a5a6e0e6ccbf4160f4
// flow-typed version: <<STUB>>/@types/graphql_v^0.8.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/graphql' {
  declare module.exports: any;
}
