// flow-typed signature: b1654ff05663ff13585174bc6b89f183
// flow-typed version: <<STUB>>/@types/inquirer_v^0.0.32/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/inquirer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/inquirer' {
  declare module.exports: any;
}
