// flow-typed signature: 63431addcdee274c55dc70ac6c923378
// flow-typed version: <<STUB>>/@types/inquirer_v^0.0.32/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/inquirer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/inquirer' {
  declare module.exports: any;
}
