// flow-typed signature: 118beb80856c69dd40c3143d1ee40fa0
// flow-typed version: <<STUB>>/@types/jest_v^16.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
