// flow-typed signature: fa740861723bf4a3c695cb3754c6754a
// flow-typed version: <<STUB>>/@types/jest_v^16.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
