// flow-typed signature: f9c55f8ac7647aad8c7caaf06939e30d
// flow-typed version: <<STUB>>/@types/mongodb_v^2.1.36/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mongodb' {
  declare module.exports: any;
}
