// flow-typed signature: 161681dffa4c09933de031db8417509c
// flow-typed version: <<STUB>>/@types/mongodb_v^2.1.36/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mongodb' {
  declare module.exports: any;
}
