// flow-typed signature: 0933ab1a3c0ed0b570035ff6b85b74cd
// flow-typed version: <<STUB>>/@types/morgan_v^1.7.32/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/morgan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/morgan' {
  declare module.exports: any;
}
