// flow-typed signature: bc4560d610a395ca1574cb39d34de996
// flow-typed version: <<STUB>>/@types/request_v^0.0.36/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request' {
  declare module.exports: any;
}
