// flow-typed signature: 350e73d7997e5c7f39bf676371e262dc
// flow-typed version: <<STUB>>/@types/request_v^0.0.39/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request' {
  declare module.exports: any;
}
