// flow-typed signature: cd00a4d8da6dbce03672c4fe8a996568
// flow-typed version: <<STUB>>/@types/rimraf_v^0.0.28/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/rimraf' {
  declare module.exports: any;
}
