// flow-typed signature: f27e1820b43d2b09158e0f41d2ff3ba5
// flow-typed version: <<STUB>>/@types/type-detect_v^0.1.28/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/type-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/type-detect' {
  declare module.exports: any;
}
