// flow-typed signature: edb5ea19bef374fc742bd7f494213f7c
// flow-typed version: <<STUB>>/@types/type-detect_v^0.1.28/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/type-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/type-detect' {
  declare module.exports: any;
}
