// flow-typed signature: d13f03e1d8d5772cced0c5cbd9287432
// flow-typed version: <<STUB>>/@types/winston_v^0.0.32/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/winston' {
  declare module.exports: any;
}
