// flow-typed signature: ae6fb081246e4c9c67d5b065b0630710
// flow-typed version: <<STUB>>/@types/winston_v^0.0.32/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/winston' {
  declare module.exports: any;
}
