// flow-typed signature: bf7e4cfaf5d21abdd7cae222381b02d7
// flow-typed version: <<STUB>>/movie-api_v^0.5.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'movie-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'movie-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'movie-api/lib/env' {
  declare module.exports: any;
}

declare module 'movie-api/lib/imdb/connector' {
  declare module.exports: any;
}

declare module 'movie-api/lib/imdb/index' {
  declare module.exports: any;
}

declare module 'movie-api/lib/index' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/cinemaInfoFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/connector' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/filmCreditsFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/filmGalleryFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/filmIdFromSearchResults' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/filmInfoFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/filmInfoListFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/index' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/types' {
  declare module.exports: any;
}

declare module 'movie-api/lib/kinopoisk/utils' {
  declare module.exports: any;
}

declare module 'movie-api/lib/test-utils' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/connector' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/creditsFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/index' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/movieInfoFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/tvShowInfoFromRes' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/types' {
  declare module.exports: any;
}

declare module 'movie-api/lib/tmdb/utils' {
  declare module.exports: any;
}

declare module 'movie-api/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'movie-api/lib/env.js' {
  declare module.exports: $Exports<'movie-api/lib/env'>;
}
declare module 'movie-api/lib/imdb/connector.js' {
  declare module.exports: $Exports<'movie-api/lib/imdb/connector'>;
}
declare module 'movie-api/lib/imdb/index.js' {
  declare module.exports: $Exports<'movie-api/lib/imdb/index'>;
}
declare module 'movie-api/lib/index.js' {
  declare module.exports: $Exports<'movie-api/lib/index'>;
}
declare module 'movie-api/lib/kinopoisk/cinemaInfoFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/cinemaInfoFromRes'>;
}
declare module 'movie-api/lib/kinopoisk/connector.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/connector'>;
}
declare module 'movie-api/lib/kinopoisk/filmCreditsFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/filmCreditsFromRes'>;
}
declare module 'movie-api/lib/kinopoisk/filmGalleryFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/filmGalleryFromRes'>;
}
declare module 'movie-api/lib/kinopoisk/filmIdFromSearchResults.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/filmIdFromSearchResults'>;
}
declare module 'movie-api/lib/kinopoisk/filmInfoFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/filmInfoFromRes'>;
}
declare module 'movie-api/lib/kinopoisk/filmInfoListFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/filmInfoListFromRes'>;
}
declare module 'movie-api/lib/kinopoisk/index.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/index'>;
}
declare module 'movie-api/lib/kinopoisk/types.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/types'>;
}
declare module 'movie-api/lib/kinopoisk/utils.js' {
  declare module.exports: $Exports<'movie-api/lib/kinopoisk/utils'>;
}
declare module 'movie-api/lib/test-utils.js' {
  declare module.exports: $Exports<'movie-api/lib/test-utils'>;
}
declare module 'movie-api/lib/tmdb/connector.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/connector'>;
}
declare module 'movie-api/lib/tmdb/creditsFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/creditsFromRes'>;
}
declare module 'movie-api/lib/tmdb/index.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/index'>;
}
declare module 'movie-api/lib/tmdb/movieInfoFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/movieInfoFromRes'>;
}
declare module 'movie-api/lib/tmdb/tvShowInfoFromRes.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/tvShowInfoFromRes'>;
}
declare module 'movie-api/lib/tmdb/types.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/types'>;
}
declare module 'movie-api/lib/tmdb/utils.js' {
  declare module.exports: $Exports<'movie-api/lib/tmdb/utils'>;
}
declare module 'movie-api/lib/utils.js' {
  declare module.exports: $Exports<'movie-api/lib/utils'>;
}
