// flow-typed signature: 0e124242dd3b482b109fd14e9ab6abeb
// flow-typed version: <<STUB>>/slugify_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slugify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slugify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'slugify/index' {
  declare module.exports: $Exports<'slugify'>;
}
declare module 'slugify/index.js' {
  declare module.exports: $Exports<'slugify'>;
}
