// flow-typed signature: 2a5edc4e0c491c4ec1b78f3d494ae76d
// flow-typed version: <<STUB>>/thepiratebay_v^1.3.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thepiratebay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'thepiratebay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thepiratebay/lib/Parser' {
  declare module.exports: any;
}

declare module 'thepiratebay/lib/thepiratebay' {
  declare module.exports: any;
}

declare module 'thepiratebay/lib/Torrent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thepiratebay/index' {
  declare module.exports: $Exports<'thepiratebay'>;
}
declare module 'thepiratebay/index.js' {
  declare module.exports: $Exports<'thepiratebay'>;
}
declare module 'thepiratebay/lib/Parser.js' {
  declare module.exports: $Exports<'thepiratebay/lib/Parser'>;
}
declare module 'thepiratebay/lib/thepiratebay.js' {
  declare module.exports: $Exports<'thepiratebay/lib/thepiratebay'>;
}
declare module 'thepiratebay/lib/Torrent.js' {
  declare module.exports: $Exports<'thepiratebay/lib/Torrent'>;
}
