// flow-typed signature: aabd31d31552b9fced9c68ef3325bdf7
// flow-typed version: <<STUB>>/winston-papertrail_v^1.0.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-papertrail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-papertrail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-papertrail/lib/winston-papertrail' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-papertrail/lib/winston-papertrail.js' {
  declare module.exports: $Exports<'winston-papertrail/lib/winston-papertrail'>;
}
